"""Turn the FreeCAD playfield SVG into a tiny JS data file the site can draw path by path."""
import json, re, sys

SRC = "C:/Users/jakub/Desktop/KdG/fablab/SketchMiddleNew.svg"
OUT = "C:/Users/jakub/Desktop/PORTFOLIO/site/js/playfield-data.js"

svg = open(SRC, encoding="utf8").read()
tags = set(re.findall(r"<(\w+)", svg)) - {"svg", "g", "path", "circle", "title"}
if tags:
    sys.exit(f"unexpected SVG elements: {tags}")
view = re.search(r'viewBox="([^"]+)"', svg).group(1)
tf = re.search(r'<g id="[^"]+" transform="([^"]+)"', svg).group(1)
tf = re.sub(r"[,]", " ", tf)
paths = [re.sub(r"\s+", " ", d).strip() for d in re.findall(r'<path\s+id="[^"]+"\s+d="([^"]+)"', svg)]
circles = [[round(float(v), 2) for v in m] for m in re.findall(r'<circle cx="([^"]+)" cy="([^"]+)" r="([^"]+)"', svg)]
data = {"viewBox": view, "transform": tf, "paths": paths, "circles": circles}
with open(OUT, "w", encoding="utf8") as f:
    f.write("/* Playfield outline exported from FreeCAD (SketchMiddleNew.svg). Generated by tools/make_playfield_js.py */\n")
    f.write("window.PLAYFIELD = " + json.dumps(data) + ";\n")
print("paths:", len(paths), "| circles:", len(circles), "| viewBox:", view, "| transform:", tf)
