// Mechanical build: keep the reusable demo's styles inside its case-study island.
import { readFileSync, writeFileSync } from 'node:fs';
const source = readFileSync(new URL('../site/css/locker-demo.css', import.meta.url), 'utf8').replace(/\/\*[\s\S]*?\*\//g, '');
function scope(css) {
  let output = '', start = 0;
  while (start < css.length) {
    const open = css.indexOf('{', start);
    if (open < 0) break;
    const header = css.slice(start, open).trim();
    let depth = 1, end = open + 1, quote = '';
    for (; end < css.length && depth; end++) {
      const char = css[end];
      if (quote) { if (char === quote && css[end - 1] !== '\\') quote = ''; continue; }
      if (char === '"' || char === "'") { quote = char; continue; }
      if (char === '{') depth++;
      if (char === '}') depth--;
    }
    const body = css.slice(open + 1, end - 1);
    if (/^@(media|supports|container)/.test(header)) output += `${header}{${scope(body)}}\n`;
    else if (header.startsWith('@')) output += `${header}{${body}}\n`;
    else {
      // Split only top-level commas, not :is(), attribute strings or gradients.
      let level = 0, selectors = [], part = '';
      for (const char of header) {
        if (char === '(' || char === '[') level++;
        if (char === ')' || char === ']') level--;
        if (char === ',' && level === 0) { selectors.push(part); part = ''; } else part += char;
      }
      selectors.push(part);
      output += selectors.map(selector => /^(body|main)$/.test(selector.trim()) ? ':where(.locker-lab)' : `:where(.locker-lab) ${selector.trim()}`).join(',') + `{${body}}\n`;
    }
    start = end;
  }
  return output;
}
writeFileSync(new URL('../site/css/locker-lab.css', import.meta.url), '/* Generated by tools/scope_locker_css.mjs. Edit locker-demo.css instead. */\n' + scope(source));
